./interproscan.sh -appl Pfam -i pep/Aha11.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Aha11/ -b annotation/Aha11.pep
./interproscan.sh -appl Pfam -i pep/Aly1.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Aly1/ -b annotation/Aly1.pep
./interproscan.sh -appl Pfam -i pep/Aly21.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Aly21/ -b annotation/Aly21.pep
./interproscan.sh -appl Pfam -i pep/Ath10.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Ath10/ -b annotation/Ath10.pep
./interproscan.sh -appl Pfam -i pep/Bju15.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Bju15/ -b annotation/Bju15.pep
./interproscan.sh -appl Pfam -i pep/Bna20.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Bna20/ -b annotation/Bna20.pep
./interproscan.sh -appl Pfam -i pep/Bna41.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Bna41/ -b annotation/Bna41.pep
./interproscan.sh -appl Pfam -i pep/BnaDAR.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/BnaDAR/ -b annotation/BnaDAR.pep
./interproscan.sh -appl Pfam -i pep/BnaZS11.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/BnaZS11/ -b annotation/BnaZS11.pep
./interproscan.sh -appl Pfam -i pep/Bni11.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Bni11/ -b annotation/Bni11.pep
./interproscan.sh -appl Pfam -i pep/Bni20.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Bni20/ -b annotation/Bni20.pep
./interproscan.sh -appl Pfam -i pep/BOERET.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/BOERET/ -b annotation/BOERET.pep
./interproscan.sh -appl Pfam -i pep/BOESTR.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/BOESTR/ -b annotation/BOESTR.pep
./interproscan.sh -appl Pfam -i pep/BOL11.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/BOL11/ -b annotation/BOL11.pep
./interproscan.sh -appl Pfam -i pep/BOL20.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/BOL20/ -b annotation/BOL20.pep
./interproscan.sh -appl Pfam -i pep/BOLHDEM.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/BOLHDEM/ -b annotation/BOLHDEM.pep
./interproscan.sh -appl Pfam -i pep/Brapa15.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Brapa15/ -b annotation/Brapa15.pep
./interproscan.sh -appl Pfam -i pep/Brapa25.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Brapa25/ -b annotation/Brapa25.pep
./interproscan.sh -appl Pfam -i pep/Brapa30.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Brapa30/ -b annotation/Brapa30.pep
./interproscan.sh -appl Pfam -i pep/BrapaZ1.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/BrapaZ1/ -b annotation/BrapaZ1.pep
./interproscan.sh -appl Pfam -i pep/Carhr10.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Carhr10/ -b annotation/Carhr10.pep
./interproscan.sh -appl Pfam -i pep/Cgr.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Cgr/ -b annotation/Cgr.pep
./interproscan.sh -appl Pfam -i pep/Chi11.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Chi11/ -b annotation/Chi11.pep
./interproscan.sh -appl Pfam -i pep/Cru11.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Cru11/ -b annotation/Cru11.pep
./interproscan.sh -appl Pfam -i pep/Csa10.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Csa10/ -b annotation/Csa10.pep
./interproscan.sh -appl Pfam -i pep/Dso11.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Dso11/ -b annotation/Dso11.pep
./interproscan.sh -appl Pfam -i pep/Esa10.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Esa10/ -b annotation/Esa10.pep
./interproscan.sh -appl Pfam -i pep/Iin.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Iin/ -b annotation/Iin.pep
./interproscan.sh -appl Pfam -i pep/Lal10.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Lal10/ -b annotation/Lal10.pep
./interproscan.sh -appl Pfam -i pep/Ovi.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Ovi/ -b annotation/Ovi.pep
./interproscan.sh -appl Pfam -i pep/Rsa10.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Rsa10/ -b annotation/Rsa10.pep
./interproscan.sh -appl Pfam -i pep/Sir10.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Sir10/ -b annotation/Sir10.pep
./interproscan.sh -appl Pfam -i pep/Spa10.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Spa10/ -b annotation/Spa10.pep
./interproscan.sh -appl Pfam -i pep/Tar11.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Tar11/ -b annotation/Tar11.pep
./interproscan.sh -appl Pfam -i pep/Tha10.pep -iprlookup -goterms -f tsv -dp -pa -dra -T temp/Tha10/ -b annotation/Tha10.pep
